services:
  app:
    image: movies-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '5000:5000'
    environment:
      NODE_ENV: development
      PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 123
      DB_DATABASE: movies_db
      DB_HOSTNAME: mysql_server
    depends_on:
      mysql_server:
        condition: service_healthy
    restart: always

  mysql_server:
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: movies_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3306']
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
